name: pl_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  image_picker: ^1.2.1
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true # This must be here for icons to work

  assets:
    - assets/images/ # This includes all files in the assets folder
    # - assets/images/ # Use this if your images are in a subfolder